# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
